### ISSUE TITLE
Add user guide: Defining and parametrizing benchmarks by applying decorators

### ISSUE THREAD

**Issue by Maciej818** [aai-institute/nnbench#34]
Add user guide to the documentation:
- [ ] Defining and parametrizing benchmarks by applying decorators (`@benchmark,@parametrize,@product)` - motivation, behavior, and one usage example for each.

**Comment by Maciej818** [comment]
To keep information complete I copy-paste here comments from #33 (which is an issue that duplicates this one):

[msavinash](https://github.com/msavinash) commented [15 hours ago](https://github.com/aai-institute/nnbench/issues/33#issuecomment-1919734401)
I don't understand how parametrize is supposed to work. From my understanding its something like this:

parametrize_parameters = [
    {"y_test": [1, 2, 3], "y_pred": [4, 5, 6]},
    {"y_test": [1, 2, 3], "y_pred": [1, 2, 3]},
]

@nnbench.parametrize(parameters=parametrize_parameters)
def accuracy(model: base.BaseEstimator, y_test: np.ndarray, y_pred: np.ndarray) -> float:
    accuracy = metrics.accuracy_score(y_test, y_pred)
    return accuracy

Is this accurate?

[nicholasjng](https://github.com/nicholasjng) commented [31 minutes ago](https://github.com/aai-institute/nnbench/issues/33#issuecomment-1920894539)
Is this accurate?

Yes.

(The arguments in the decorator dictionaries should match the parametrized benchmark function's typing, so the arguments should be np.array([1, 2, 3]),  np.array([4, 5, 6]), ..., but you got it right conceptually.)

**Comment by msavinash** [comment]
I tried running this:
`from nnbench import runner
import nnbench
from sklearn import base
import numpy as np


parametrize_parameters = [
    {"y_test": np.array([1, 2, 3]), "y_pred": np.array([4, 5, 6])},
    {"y_test": np.array([1, 2, 3]), "y_pred": np.array([1, 2, 3])},
]

@nnbench.parametrize(parameters=parametrize_parameters)
def accuracy(model: base.BaseEstimator, y_test: np.ndarray, y_pred: np.ndarray) -> float:
    accuracy = metrics.accuracy_score(y_test, y_pred)
    return accuracy


from nnbench import runner
r = runner.BenchmarkRunner()
y_pred = model.predict(X_test)
result = r.run("__main__", params={"model": model})

r.report(to='console', result=result)`


Got this error:
`ValueError: missing value for required parameter 'y_test'`

I believe the code expects me to add y_pred and y_test as well, but they are defined for parameterize decorator. What is the expected behavior here?
`result = r.run("__main__", params={"model": model, "y_pred": y_pred, "y_test": y_test})`
