### ISSUE TITLE
Add example: Implement benchmarking on saved artifacts

### ISSUE THREAD

**Issue by Maciej818** [aai-institute/nnbench#63]
- [ ] Performance diffing by materializing older versions of a model and then comparing accuracy on a different evaluation set (needs design of artifact sourcing, download, materialization).

**Comment by nicholasjng** [comment]
I think that based on the description, this should be broken into at least two steps.

First off, we should create an example of a benchmark that is run against a saved model. That can be as simple as going into a previously created folder on disk, loading a model (ideally saving multiple models in different artifact locations), and then running benchmarks on it by passing it as a `param`. (Bonus points for a custom name generation, since models usually don't have nice `__str__()/__repr__()` methods).

Then, after a single benchmark test, we could move to the parametrized test, e.g. parametrizing by folders / artifact names (at that point, it might make sense to look into an `Artifact` class and try to materialize it, maybe in a setup task).

And lastly, once you have the record(s) in hand, we need to compare results across models. This needs to be done by a custom data preprocessor that takes a record and creates a new one out of it, with custom columns (e.g. comparing accuracies to an "anchor"/reference model. Some inspiration for custom columns (at least the basics, don't take over this functional disaster from there) can be found here: https://github.com/nicholasjng/pybm/tree/master/pybm/reporters
