### ISSUE TITLE
Streaming results to a database: verify SQL model, decide on what API to go forward

### ISSUE THREAD

**Issue by Maciej818** [aai-institute/nnbench#86]
This two subtasks separated from #66 :
- [x] Check/verify SQL model.
- [ ] Decide on what API we go forward with.

**Comment by nicholasjng** [comment]
There is a split here in terms of difficulty and usefulness for different SQL APIs that we have to keep in mind before we formalize the SQL sink(s).

On the one hand, a "raw" SQL API taking queries and forwarding them to a client takes almost no implementation effort (outside of validating some query aspects like INSERTs for uploads, SELECTs for downloads). Those APIs will then be limited in usefulness, however - outside of a few preprocessing aspects and client polymorphism, they provide no value for the user.

On the other hand, an ORM model API makes things more Pythonic and type-safe, but requires potentially much more implementation effort, and needs dynamic features to work for us at least on upload, since the BenchmarkRecords will have different entries based on what context you give. It also requires dependencies like SQLModel / SQLAlchemy for ORM construction, and (in this case) DB engine packages for being able to speak to different databases through SQLAlchemy.

I'm inclined to go with case 1) for now, since it works well enough even now, provided that Python interfaces to your target DBs can deal with Python dictionaries and/or JSON data.

If there is a need/request for ORM SQL, we can revisit this later. We have a working example for BQ already, I'd say that if we make one for duckDB (where we would write a NDJSON flatfile and ingest from it, with schema inference and all goodies without any effort), we're golden.

Would love to hear @maxmynter and @janwillemkl 's opinions as well.

**Comment by janwillemkl** [comment]
I agree going with option 1.

Providing the raw SQL interface will give the user full flexibility, so it makes sense to provide that anyway. 

As you say, we can always build the ORM interface in addition later.
